FROM node:26-alpine AS development-dependencies-env
COPY frontend/package.json /app/frontend/
COPY package.json package-lock.json /app/
WORKDIR /app/
RUN npm ci

FROM node:26-alpine AS production-dependencies-env
COPY frontend/package.json /app/frontend/
COPY package.json package-lock.json /app/
WORKDIR /app/
RUN npm ci --omit=dev

FROM node:26-alpine AS build-env
ARG VITE_BACKEND_URL
ENV VITE_BACKEND_URL=${VITE_BACKEND_URL}
COPY --from=development-dependencies-env /app/node_modules /app/node_modules
COPY frontend /app/frontend
WORKDIR /app/frontend
RUN npm run build

FROM busybox:latest AS deploy
WORKDIR /apptemp
COPY --from=build /app/frontend/build/client /apptemp

CMD ["/bin/sh", "-c", "mkdir -p /var/www/skybridge.bonnybonnybonaktan.xyz && cp -R /apptemp/* /var/www/skybridge.bonnybonnybonaktan.xyz"]